-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghuZYGAaLpxdmtKzl
AnYoi0XErMtSrCHTOJCCcC8PBvKgCgYIKoZIzj0DAQehRANCAAS3TwVz6B7OVKr0
NTQ3ELSHaAJfSWWDMG2u2gwu2QLq0rU+FADZuCY4/shGmEGuPiBLugHUVqsfJ+Dy
BROz45eQ
-----END PRIVATE KEY-----